name: photon_exodus_web
description: The web interface for Project Loom.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  http: ^1.2.0
flutter:
  uses-material-design: true
